[package]
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "group_by"
repository = "https://github.com/Terkwood/group_by.rs"
version = "0.1.0"

[dependencies]
